spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

server:
  port: 19010

eureka:
  client:
    service-url:
      # docker-compose 작업 후 localhost를  서비스명으로 변경
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true
