spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

server:
  port: 19010

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:19090}/eureka/
    register-with-eureka: true
    fetch-registry: true
