server:
  port: 19020

spring:
  application:
    name: user-service
  profiles:
    active: local

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

eureka:
  client:
    enabled: false

keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://keycloak:8080}
  realm: ${KEYCLOAK_REALM:hub-delivery}
  client-id: ${KEYCLOAK_CLIENT_ID:hub-delivery-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:}
  admin:
    realm: ${KEYCLOAK_ADMIN_REALM:master}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:}
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${USER_DB:user_db}
    username: ${POSTGRES_USER:hub}
    password: ${POSTGRES_PASSWORD:hub}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${USER_DB:user_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
